---
secrets_list:
  - app_name: "{{ flyio_app_name }}"
    secrets:
      - name: NATS_CLUSTER_TOKEN
        value: "{{ flyio_flynet_nats_cluster_token }}"
      - name: NATS_ROUTE_FRA
        value: "{{ flynet_nats.cluster.routes.fra }}"
      - name: NATS_ROUTE_IAD
        value: "{{ flynet_nats.cluster.routes.iad }}"
      - name: NATS_ROUTE_ORD
        value: "{{ flynet_nats.cluster.routes.ord }}"
      - name: NATS_TOKEN
        value: "{{ flyio_flynet_botnats_nats_token }}"
...
