---
volumes_api_token: "{{ flyio_api_token }}"
volumes_info_api_token: "{{ flyio_api_token }}"
volumes_info_app_name: "{{ flyio_app_name }}"

volumes_list:
  - app_name: "{{ flyio_app_name }}"
    volumes:
      - name: "{{ flyio_region }}"
        region: "{{ flyio_region }}"
        size_gb: 1
...
