---
machines_list:
  - app_name: "{{ flyio_app_name }}"
    env:
      BOTNATS_NATS_CLUSTER_ADVERTISE: >-
        {{ flyio_region }}.{{ flyio_app_name }}.internal:6222
      BOTNATS_NATS_SERVER_NAME: "{{ inventory_hostname }}"
      BOTNATS_NATS_TOKEN: "{{ flyio_flynet_nats_token }}"
    files:
      - guest_path: /nats-server.conf
        raw_value: >-
          {{ lookup('template', 'nats-server.conf.j2') | b64encode }}
    checks:
      healthz:
        type: http
        port: 8222
        path: /healthz?js-enabled-only=true
        interval: 10s
        timeout: 2s
    guest:
      cpu_kind: shared
      cpus: 1
      memory_mb: 256
    image: nats:2.14.0-alpine
    mounts:
      - volume: >-
          {{ (_volumes_info_list |
              selectattr('name', 'equalto', flyio_region) |
              selectattr('state', 'equalto', 'created') |
              first).id }}
        path: /data
    init:
      cmd:
        - exec nats-server --config /nats-server.conf
      entrypoint:
        - /bin/sh
        - -c
    name: "{{ inventory_hostname }}"
    region: "{{ flyio_region }}"
...
