---
nats_routes:
  - nats://flynet:{{ flyio_flynet_nats_token }}@nats-fra.internal:6222
  - nats://flynet:{{ flyio_flynet_nats_token }}@nats-iad.internal:6222
  - nats://flynet:{{ flyio_flynet_nats_token }}@nats-ord.internal:6222
...
