---
all:
  children:
    nats:
      hosts:
        flynet-nats:
          flyio_region: ord
        flynet-nats-fra:
          flyio_region: fra
        flynet-nats-iad:
          flyio_region: iad
    flynet:
      hosts:
        balerion:
          flyio_region: dfw
        caraxes:
          flyio_region: ewr
        drogon:
          flyio_region: ams
        rhaegal:
          flyio_region: lhr
        sunfyre:
          flyio_region: lax
        vhagar:
          flyio_region: sjc
        viserion:
          flyio_region: arn
...
