---
all:
  children:
    nats:
      vars:
        flyio_app_name: flynats
      hosts:
        nats-fra:
          flyio_region: fra
        nats-iad:
          flyio_region: iad
        nats-ord:
          flyio_region: ord
    flynet:
      vars:
        flyio_app_name: flybots
      hosts:
        balerion:
          flyio_region: dfw
        caraxes:
          flyio_region: ewr
        drogon:
          flyio_region: ams
        rhaegal:
          flyio_region: lhr
        sunfyre:
          flyio_region: lax
        vhagar:
          flyio_region: sjc
        viserion:
          flyio_region: arn
...
