---
all:
  children:
    nats:
      hosts:
        flynet-nats:
          flyio_region: ord
        flynet-nats-fra:
          flyio_region: fra
        flynet-nats-iad:
          flyio_region: iad
    flynet:
      hosts:
        balerion:
          flyio_region: ord
        vhagar:
          flyio_region: iad
        meraxes:
          flyio_region: dfw
        vermithor:
          flyio_region: sjc
        dreamfyre:
          flyio_region: lax
        caraxes:
          flyio_region: ewr
        sunfyre:
          flyio_region: fra
...
