---
apps_api_token: "{{ flyio_api_token }}"

apps_info_api_token: "{{ flyio_api_token }}"
apps_info_org_slug: "{{ flyio_org_slug }}"

apps_list:
  - name: "{{ inventory_hostname }}"
    network: flynet
    org_slug: "{{ flyio_org_slug }}"
...
