---
flyio_api_token:
  "{{ lookup('amazon.aws.ssm_parameter', '/flyio/api/token') }}"

flyio_flynet_coordination_secret:
  "{{ lookup('amazon.aws.ssm_parameter', '/flyio/flynet/coordination/secret') }}"

flyio_flynet_nats_token:
  "{{ lookup('amazon.aws.ssm_parameter', '/flyio/flynet/nats/token') }}"

flyio_flynet_totp_secret:
  "{{ lookup('amazon.aws.ssm_parameter', '/flyio/flynet/irc/totp/secret') }}"

flyio_org_slug:
  "{{ lookup('amazon.aws.ssm_parameter', '/flyio/org/slug') }}"
...
