---
machines_list:
  - app_name: "{{ flyio_app_name }}"
    machines:
      - checks:
          health:
            grace_period: 30s
            interval: 15s
            path: /
            port: 8080
            timeout: 5s
            type: http
        files:
          - guest_path: /etc/botnats/bot.json
            raw_value: >-
              {{ lookup('template', 'bot.json.j2') | b64encode }}
        guest:
          cpu_kind: shared
          cpus: 1
          memory_mb: 256
        image: "{{ flynet_botnats.image }}"
        name: "{{ inventory_hostname }}"
        region: "{{ flyio_region }}"
        restart:
          policy: always
...
