---
secrets_list:
  - app_name: "{{ flyio_app_name }}"
    secrets:
      - name: BOTNATS_COORDINATION_SECRET
        value: "{{ flyio_flynet_botnats_coordination_secret }}"
      - name: BOTNATS_NATS_TOKEN
        value: "{{ flyio_flynet_botnats_nats_token }}"
      - name: BOTNATS_TOTP_SECRET
        value: "{{ flyio_flynet_botnats_totp_secret }}"
...
