---
flynet_channel_modes: "+npst"
flynet_image: ghcr.io/tkimball83/botnats:v0.0.8
flynet_network: undernet
flynet_irc_servers:
  - irc://eu6.undernet.org:6667
  - irc://us6.undernet.org:6667
flynet_nats_servers:
  - nats://nats-fra.internal:4222
  - nats://nats-iad.internal:4222
  - nats://nats-ord.internal:4222
...
