---
flynet_image: ghcr.io/tkimball83/botnats:sha-3a7c268
flynet_network: efnet
flynet_irc_servers:
  - ircs://efnet.deic.eu:6697
  - ircs://efnet.tngnet.nl:6697
  - ircs://irc.choopa.net:6697
  - ircs://irc.efnet.nl:6697
  - ircs://irc.mzima.net:6697
  - ircs://irc.swepipe.se:6697
  - ircs://irc.underworld.no:6697
flynet_nats_servers:
  - nats://nats-fra.internal:4222
  - nats://nats-iad.internal:4222
  - nats://nats-ord.internal:4222
...
