---
- name: Ensure flynet nats are deployed
  hosts: nats
  gather_facts: false
  roles:
    - linuxhq.flyio.apps
    - linuxhq.flyio.machines

- name: Ensure flynet bots are deployed
  hosts: flynet
  serial: 1
  gather_facts: false
  roles:
    - linuxhq.flyio.apps
    - linuxhq.flyio.machines
...
