---
- name: Ensure flynet flybots app is absent
  hosts: flybots[0]
  gather_facts: false
  roles:
    - role: linuxhq.flyio.apps
      apps_list:
        - name: "{{ flyio_app_name }}"
          org_slug: "{{ flyio_org_slug }}"
          state: absent

- name: Ensure flynet flynats app is absent
  hosts: flynats[0]
  gather_facts: false
  roles:
    - role: linuxhq.flyio.apps
      apps_list:
        - name: "{{ flyio_app_name }}"
          org_slug: "{{ flyio_org_slug }}"
          state: absent
...
