---
- name: Ensure flynet flynats app is absent
  hosts: flynats
  gather_facts: false
  roles:
    - role: linuxhq.flyio.apps
      apps_list:
        - name: "{{ flyio_app_name }}"
          org_slug: "{{ flyio_org_slug }}"
          state: absent
      run_once: true

- name: Ensure flynet flybots app is absent
  hosts: flybots
  gather_facts: false
  roles:
    - role: linuxhq.flyio.apps
      apps_list:
        - name: "{{ flyio_app_name }}"
          org_slug: "{{ flyio_org_slug }}"
          state: absent
      run_once: true
...
