---
- name: Ensure flynet flybots app is deployed
  hosts: flybots
  gather_facts: false
  roles:
    - role: linuxhq.flyio.apps
      run_once: true

- name: Ensure flynet flybots machines are deployed
  hosts: flybots
  serial: 1
  gather_facts: false
  roles:
    - linuxhq.flyio.machines
    - linuxhq.flyio.machines_info

  post_tasks:
    - name: Ensure bot dependency readiness
      linuxhq.flyio.machines_exec:
        api_token: "{{ machines_info_api_token }}"
        app_name: "{{ flyio_app_name }}"
        command: wget -qO- http://localhost:8080/ready
        id: "{{ _machines_info_dict[inventory_hostname].id }}"
      register: __flybots_result
      until: __flybots_result.stdout | default('') == 'ok'
      retries: 30
      delay: 5
      changed_when: false
...
