---
ansible_connection: local
ansible_python_interpreter: "{{ ansible_playbook_python }}"

apps_api_token: "{{ flyio_api_token }}"

apps_info_api_token: "{{ flyio_api_token }}"
apps_info_org_slug: "{{ flyio_org_slug }}"

apps_list:
  - name: "{{ inventory_hostname }}"
    network: flynet
    org_slug: "{{ flyio_org_slug }}"

machines_api_token: "{{ flyio_api_token }}"

machines_info_api_token: "{{ flyio_api_token }}"
machines_info_app_name: "{{ inventory_hostname }}"

nats_routes:
  - nats://flynet:{{ flyio_flynet_nats_token }}@nats-fra.internal:6222
  - nats://flynet:{{ flyio_flynet_nats_token }}@nats-iad.internal:6222
  - nats://flynet:{{ flyio_flynet_nats_token }}@nats-ord.internal:6222

machines_list:
  - app_name: "{{ inventory_hostname }}"
    env:
      BOTNATS_NATS_CLUSTER_ADVERTISE: "{{ inventory_hostname }}.internal:6222"
      BOTNATS_NATS_SERVER_NAME: "{{ inventory_hostname }}"
      BOTNATS_NATS_TOKEN: "{{ flyio_flynet_nats_token }}"
    files:
      - guest_path: /nats-server.conf
        raw_value: >-
          {{ lookup('template', 'nats-server.conf.j2') | b64encode }}
    checks:
      healthz:
        type: http
        port: 8222
        path: /healthz
        interval: "10s"
        timeout: "2s"
    guest:
      cpu_kind: shared
      cpus: 1
      memory_mb: 256
    image: nats:2.14.0-alpine
    init:
      cmd:
        - exec nats-server --config /nats-server.conf
      entrypoint:
        - /bin/sh
        - -c
    name: "{{ inventory_hostname }}"
    region: "{{ flyio_region }}"
...
